#!/bin/bash
cd /home/jcz/Documents/github/weather
python3 all_sites_weekly_temps.py
python3 e1248weekly_temps.py
python3 e4229weekly_temps.py
python3 e4279weekly_temps.py
python3 kpwm_weekly_temps.py
python3 all_e1248weekly_temps_w_electric.py
python3 energy_stacked.py
python3 weeknum.py
python3 all_e1248weekly_temps_w_electric.py
python3 all_sites_daily_temp_ranges.py
python3 daily_e1248_temps_w_electric.py 
python3 monthly_elec_cost.py
python3 monthly_electric_cost_correlation.py
python3 monthly_elec_cost.py

python3 weekly_HDD65_elec_use_correlation_2020_after.py
python3 weekly_HDD65_elec_use_correlation_lt2020.py
python3 weekly_temp_elec_use_correlation_2020_after.py
python3 weekly_temp_elec_use_correlation_lt2020.py
./xfer.sh
